#pragma once
static const char DIR_3RD_QUIZ[][13] = { "__NAME  ._DT", "__ITEM  ._DT", "__MAGIC ._DT",
"__SE    ._DT",
"__BTSET1._DT",
"__FACE  ._DT",
"__TOWN  ._DT",
"__QUEST ._DT",
"__STATUS._DT",
"__MAGGET._DT",
"__SLTGET._DT",
"__CRFGET._DT",
"__SHOP  ._DT",
"__EXP   ._DT",
"__ITEM2 ._DT",
"__QUARTZ._DT",
"__ORB   ._DT",
"__COOK2 ._DT",
"__COOK  ._DT",
"__MEMO  ._DT",
"__BGMTBL._DT",
"__MAGQRT._DT",
"__BOOK00._DT",
"__BOOK01._DT",
"__BOOK02._DT",
"__BOOK03._DT",
"__BOOK04._DT",
"__BOOK05._DT",
"__BOOK06._DT",
"__BOOK07._DT",
"__BOOK08._DT",
"__BOOK09._DT",
"__WORLD ._DT",
"T_FISH  ._DT",
"__CHAIN ._DT",
"__QUEST1._DT",
"__MEMO1 ._DT",
"__BTSET2._DT",
"__BOOK10._DT",
"__BOOK11._DT",
"__BOOK12._DT",
"__BOOK13._DT",
"__BOOK14._DT",
"__BOOK15._DT",
"__BOOK16._DT",
"__BOOK17._DT",
"__BOOK18._DT",
"__BOOK19._DT",
"__QUEST2._DT",
"__ITTXT ._DT",
"__ITTXT2._DT",
"__DROPIT._DT",
"__VOICE ._DT",
"__MMT   ._DT",
"__TITLE ._DT",
"T_QUIZ01._DT",
"T_QUIZ02._DT",
"T_QUIZ03._DT",
"__SUGO  ._DT",
"__SUGOEN._DT",
"__SUGOAN._DT",
"__MG0500._DT",
"__SUENAN._DT",
"__SUEV00._DT",
"__SUEV01._DT",
"__SUEV02._DT",
"__SUEV03._DT",
"__SUEV04._DT",
"__SUEV05._DT",
"__SUEV06._DT",
"__SUEV07._DT",
"__SUEV08._DT",
"__SUEV09._DT",
"__SUEV10._DT",
"__SUEV11._DT",
"__SUEV12._DT",
"__SUEV13._DT",
"__SUEV14._DT",
"__SUEV15._DT",
"__SUEVAL._DT",
"T_QUIZ04._DT",
"__BTREV ._DT",
};
